providers:
  - provider: kraken
    reconnect_delay_secs: 5
    max_reconnect_attempts: 5
    symbol_feeds:
      - markets: crypto
        symbol: "BTC/USD"
        feed_type: trades
      - markets: crypto
        symbol: "BTC/USD"
        feed_type: book
      - markets: crypto
        symbol: "BTC/USD"
        feed_type: orders
      - markets: crypto
        symbol: "ETC/USD"
        feed_type: trades
      - markets: crypto
        symbol: "ETC/USD"
        feed_type: book
      - markets: crypto
        symbol: "ETC/USD"
        feed_type: orders

database_conf:
  postgres_config:
    host: localhost
    port: "5432"
    database: helixfeed_dev
    user: "CHANGE_ME"
    password: "CHANGE_ME"
  r2:
    bucket: "CHANGE_ME"
    endpoint: "https://<your-cloudflare-account-id>.r2.cloudflarestorage.com/"
    upload_schedule: "hourly"

log_config:
  feed_log_location: "logs/kraken.log"
  system_log_location: "logs/system.log"

buffer_capacity: 100
buffer_swap_trigger: 0.8
